-- ====================================================================
-- PSG College of Arts & Science - Supabase Database Schema
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard)
-- Project: https://wguboyrruvmgnxjxtufl.supabase.co
-- ====================================================================

-- 1. Create applications table
CREATE TABLE IF NOT EXISTS public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_uuid TEXT UNIQUE NOT NULL,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'Pending',
    admin_notes TEXT DEFAULT '',

    -- Position & Department
    position TEXT,
    department TEXT,

    -- Personal Details
    name TEXT,
    photo_path TEXT,
    dob TEXT,
    gender TEXT,
    mother_tongue TEXT,
    religion TEXT,
    community TEXT,
    category TEXT,
    marital_status TEXT,
    spouse_name TEXT,
    father_name TEXT,
    diff_abled TEXT,
    nature TEXT,
    aadhaar_no TEXT,
    pan_no TEXT,
    mobile_no TEXT,
    email TEXT,

    -- Address Details
    native_address TEXT,
    native_city TEXT,
    native_state TEXT,
    native_country TEXT,
    native_pincode TEXT,
    local_address TEXT,
    local_city TEXT,
    local_state TEXT,
    local_country TEXT,
    local_pincode TEXT,

    -- Sub-tables (JSON Strings)
    languages TEXT,
    education TEXT,
    teaching_experience TEXT,
    industry_experience TEXT,
    projects TEXT,
    patents TEXT,
    pdf_details TEXT,

    -- Academic Qualifications & Scores
    net TEXT,
    set_slet TEXT,
    nss TEXT,
    ncc TEXT,
    naac TEXT,
    iqac TEXT,
    iso TEXT,
    achivements TEXT,

    -- Research & Publications
    sci TEXT,
    scopus TEXT,
    ugc TEXT,
    others TEXT,
    scopus_id TEXT,
    h_index_google TEXT,
    h_index_scopus TEXT,
    books_published_national TEXT,
    books_published_international TEXT,
    books_edited_national TEXT,
    books_edited_international TEXT,
    papers_path TEXT,
    chapters_published_national TEXT,
    chapters_published_international TEXT,
    chapters_edited_national TEXT,
    chapters_edited_international TEXT,
    minor_projects TEXT,
    major_projects TEXT,
    patents_applied TEXT,
    patents_published TEXT,
    patents_granted TEXT,
    consultancy TEXT,

    -- References
    name_1 TEXT,
    address_1 TEXT,
    designation_1 TEXT,
    mobile_1 TEXT,
    email_1 TEXT,
    name_2 TEXT,
    address_2 TEXT,
    designation_2 TEXT,
    mobile_2 TEXT,
    email_2 TEXT,

    -- Additional Information
    last_pay TEXT,
    pay_expected TEXT,
    join_time TEXT,
    relative TEXT,
    already_attended TEXT,
    huk TEXT,
    comments TEXT,
    resume_path TEXT
);

-- 2. Create staff / admins table for Supabase
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('secretary', 'vice_principal', 'viewer', 'editor')),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed default staff
INSERT INTO public.staff (email, role, name)
VALUES 
    ('secretary@psgcas.ac.in', 'secretary', 'Secretary'),
    ('vp@psgcas.ac.in', 'vice_principal', 'Vice Principal')
ON CONFLICT (email) DO NOTHING;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;

-- 4. Create policies to allow public submissions & staff access via API
DROP POLICY IF EXISTS "Public can submit applications" ON public.applications;
CREATE POLICY "Public can submit applications"
ON public.applications FOR INSERT TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all access to applications" ON public.applications;
CREATE POLICY "Allow all access to applications"
ON public.applications FOR ALL TO anon, authenticated
USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read access to staff" ON public.staff;
CREATE POLICY "Allow read access to staff"
ON public.staff FOR SELECT TO anon, authenticated
USING (true);
